### ISSUE TITLE
😢那个面试题

### ISSUE THREAD

**Issue by ostreamBaba** [JJJTHuang/Learning#1]
自己写个sort…然后写个cmp(从小到大排，从大到小排)，为什么能逆序。

**Comment by ostreamBaba** [comment]
😂不是只能适合这道题吗，刚好字母都是 从小到大，逆序就是从大到小，这是什么骚操作。

**Comment by JJJTHuang** [comment]
对的,方法一是不严谨的,仅仅适合已经排好序的str
